"""add_description_and_null_price

Revision ID: 1cb36619217b
Revises: 1577831077cd
Create Date: 2022-06-13 01:02:00.234090

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '1cb36619217b'
down_revision = '1577831077cd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('good', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('good', 'description')
    # ### end Alembic commands ###
