"""m2m_user_categoty

Revision ID: 90cc57a7bcb5
Revises: adfd1203f9cf
Create Date: 2022-06-12 15:26:30.525933

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '90cc57a7bcb5'
down_revision = 'adfd1203f9cf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usercategory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name=op.f('fk_usercategory_category_id_category')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_usercategory_user_id_user')),
    sa.PrimaryKeyConstraint('id', 'user_id', 'category_id', name=op.f('pk_usercategory'))
    )
    op.create_index(op.f('ix_usercategory_id'), 'usercategory', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usercategory_id'), table_name='usercategory')
    op.drop_table('usercategory')
    # ### end Alembic commands ###
