"""add_email

Revision ID: 9946c74b8e69
Revises: 90cc57a7bcb5
Create Date: 2022-06-12 17:31:27.705895

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '9946c74b8e69'
down_revision = '90cc57a7bcb5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
